version: '2'

services:

  balancer:
    build:
      context: ./RoundRobin
      dockerfile: Dockerfile
    container_name: balancer
    ports:
      - "35000:6000"

  log1:
    build:
      context: ./LogService
      dockerfile: Dockerfile
    ports:
      - "35001:6000"

  db:
    image: mongo:3.6.1
    container_name: db
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - 27017:27017
    command: mongod

volumes:
  mongodb:
  mongodb_config:
