version: '2'

services:

  balancer:
    image: balancer
    container_name: balancer
    networks:
      arep-lab5_default:
        ipv4_address: 172.24.0.2
    ports:
      - "35000:6000"

  log1:
    image: logservice
    networks:
      arep-lab5_default:
        ipv4_address: 172.24.0.3

  log2:
    image: logservice
    networks:
      arep-lab5_default:
        ipv4_address: 172.24.0.4

  log3:
    image: logservice
    networks:
      arep-lab5_default:
        ipv4_address: 172.24.0.5

  db:
    image: mongo:3.6.1
    container_name: db
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    networks:
      arep-lab5_default:
        ipv4_address: 172.24.0.6
    ports:
      - 27017:27017
    command: mongod

networks:
  arep-lab5_default:
    ipam:
      driver: default
      config:
        - subnet: 172.24.0.0/16

volumes:
  mongodb:
  mongodb_config:
